# Generated by Django 4.2.11 on 2024-12-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
