# Generated by Django 4.2.11 on 2024-12-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
