# Generated by Django 4.2.11 on 2024-12-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfo', '0003_profile_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='contected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
